---
name: "Events Workflow"
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
  pull_request_target:
    branches: [main]
    types: [opened, edited, reopened]
  push:
    branches: [main]

permissions:
  pull-requests: write
  id-token: write
  contents: write

jobs:
  events:
    uses: gocloudLa/.github/.github/workflows/shared-terraform-events.yml@feature/readme-generator
    secrets: inherit


