name: Lab PR Validation

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

jobs:
  lab-pr-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        id: debug
        run: |
          echo "Debug OK !!"