name: Terraform Readme Generator

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/10 * * * *'

jobs:
  generate-readme:
    uses: gocloudLa/.github/.github/workflows/readme-generator.yml@feature/readme-generator # Remover esta ref finalizado el desarrollo
    secrets: inherit 